# CMake generated Testfile for 
# Source directory: /Users/schun/nektar/solvers/PulseWaveSolver
# Build directory: /Users/schun/nektar/buildarm/solvers/PulseWaveSolver
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(PulseWaveSolver_55_Artery_Network "/Users/schun/nektar/buildarm/tests/Tester" "/Users/schun/nektar/solvers/PulseWaveSolver/Tests/55_Artery_Network.tst")
set_tests_properties(PulseWaveSolver_55_Artery_Network PROPERTIES  _BACKTRACE_TRIPLES "/Users/schun/nektar/cmake/NektarCommon.cmake;263;ADD_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;48;ADD_NEKTAR_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;0;")
add_test(PulseWaveSolver_Bifurcation "/Users/schun/nektar/buildarm/tests/Tester" "/Users/schun/nektar/solvers/PulseWaveSolver/Tests/Bifurcation.tst")
set_tests_properties(PulseWaveSolver_Bifurcation PROPERTIES  _BACKTRACE_TRIPLES "/Users/schun/nektar/cmake/NektarCommon.cmake;263;ADD_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;49;ADD_NEKTAR_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;0;")
add_test(PulseWaveSolver_Junction "/Users/schun/nektar/buildarm/tests/Tester" "/Users/schun/nektar/solvers/PulseWaveSolver/Tests/Junction.tst")
set_tests_properties(PulseWaveSolver_Junction PROPERTIES  _BACKTRACE_TRIPLES "/Users/schun/nektar/cmake/NektarCommon.cmake;263;ADD_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;50;ADD_NEKTAR_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;0;")
add_test(PulseWaveSolver_TwoBifurcations "/Users/schun/nektar/buildarm/tests/Tester" "/Users/schun/nektar/solvers/PulseWaveSolver/Tests/TwoBifurcations.tst")
set_tests_properties(PulseWaveSolver_TwoBifurcations PROPERTIES  _BACKTRACE_TRIPLES "/Users/schun/nektar/cmake/NektarCommon.cmake;263;ADD_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;51;ADD_NEKTAR_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;0;")
add_test(PulseWaveSolver_Merging "/Users/schun/nektar/buildarm/tests/Tester" "/Users/schun/nektar/solvers/PulseWaveSolver/Tests/Merging.tst")
set_tests_properties(PulseWaveSolver_Merging PROPERTIES  _BACKTRACE_TRIPLES "/Users/schun/nektar/cmake/NektarCommon.cmake;263;ADD_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;52;ADD_NEKTAR_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;0;")
add_test(PulseWaveSolver_VariableAreaTest "/Users/schun/nektar/buildarm/tests/Tester" "/Users/schun/nektar/solvers/PulseWaveSolver/Tests/VariableAreaTest.tst")
set_tests_properties(PulseWaveSolver_VariableAreaTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/schun/nektar/cmake/NektarCommon.cmake;263;ADD_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;53;ADD_NEKTAR_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;0;")
add_test(PulseWaveSolver_VariableMatPropTest "/Users/schun/nektar/buildarm/tests/Tester" "/Users/schun/nektar/solvers/PulseWaveSolver/Tests/VariableMatPropTest.tst")
set_tests_properties(PulseWaveSolver_VariableMatPropTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/schun/nektar/cmake/NektarCommon.cmake;263;ADD_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;54;ADD_NEKTAR_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;0;")
add_test(PulseWaveSolver_QInflow "/Users/schun/nektar/buildarm/tests/Tester" "/Users/schun/nektar/solvers/PulseWaveSolver/Tests/QInflow.tst")
set_tests_properties(PulseWaveSolver_QInflow PROPERTIES  _BACKTRACE_TRIPLES "/Users/schun/nektar/cmake/NektarCommon.cmake;263;ADD_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;55;ADD_NEKTAR_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;0;")
add_test(PulseWaveSolver_RCR_boundary "/Users/schun/nektar/buildarm/tests/Tester" "/Users/schun/nektar/solvers/PulseWaveSolver/Tests/RCR_boundary.tst")
set_tests_properties(PulseWaveSolver_RCR_boundary PROPERTIES  _BACKTRACE_TRIPLES "/Users/schun/nektar/cmake/NektarCommon.cmake;263;ADD_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;56;ADD_NEKTAR_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;0;")
add_test(PulseWaveSolver_AInflow "/Users/schun/nektar/buildarm/tests/Tester" "/Users/schun/nektar/solvers/PulseWaveSolver/Tests/AInflow.tst")
set_tests_properties(PulseWaveSolver_AInflow PROPERTIES  _BACKTRACE_TRIPLES "/Users/schun/nektar/cmake/NektarCommon.cmake;263;ADD_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;57;ADD_NEKTAR_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;0;")
add_test(PulseWaveSolver_UInflow "/Users/schun/nektar/buildarm/tests/Tester" "/Users/schun/nektar/solvers/PulseWaveSolver/Tests/UInflow.tst")
set_tests_properties(PulseWaveSolver_UInflow PROPERTIES  _BACKTRACE_TRIPLES "/Users/schun/nektar/cmake/NektarCommon.cmake;263;ADD_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;58;ADD_NEKTAR_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;0;")
add_test(PulseWaveSolver_Viscoelasticity "/Users/schun/nektar/buildarm/tests/Tester" "/Users/schun/nektar/solvers/PulseWaveSolver/Tests/Viscoelasticity.tst")
set_tests_properties(PulseWaveSolver_Viscoelasticity PROPERTIES  _BACKTRACE_TRIPLES "/Users/schun/nektar/cmake/NektarCommon.cmake;263;ADD_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;59;ADD_NEKTAR_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;0;")
add_test(PulseWaveSolver_EmpiricalPressure "/Users/schun/nektar/buildarm/tests/Tester" "/Users/schun/nektar/solvers/PulseWaveSolver/Tests/EmpiricalPressure.tst")
set_tests_properties(PulseWaveSolver_EmpiricalPressure PROPERTIES  _BACKTRACE_TRIPLES "/Users/schun/nektar/cmake/NektarCommon.cmake;263;ADD_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;60;ADD_NEKTAR_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;0;")
add_test(PulseWaveSolver_PowerPressure "/Users/schun/nektar/buildarm/tests/Tester" "/Users/schun/nektar/solvers/PulseWaveSolver/Tests/PowerPressure.tst")
set_tests_properties(PulseWaveSolver_PowerPressure PROPERTIES  _BACKTRACE_TRIPLES "/Users/schun/nektar/cmake/NektarCommon.cmake;263;ADD_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;61;ADD_NEKTAR_TEST;/Users/schun/nektar/solvers/PulseWaveSolver/CMakeLists.txt;0;")
subdirs("Utilities")
