# CMake generated Testfile for 
# Source directory: /Users/schun/nektar/solvers/ShallowWaterSolver
# Build directory: /Users/schun/nektar/buildtest/solvers/ShallowWaterSolver
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ShallowWaterSolver_TestMMFSWEPlane "/Users/schun/nektar/buildtest/tests/Tester" "/Users/schun/nektar/solvers/ShallowWaterSolver/Tests/TestMMFSWEPlane.tst")
set_tests_properties(ShallowWaterSolver_TestMMFSWEPlane PROPERTIES  _BACKTRACE_TRIPLES "/Users/schun/nektar/cmake/NektarCommon.cmake;263;ADD_TEST;/Users/schun/nektar/solvers/ShallowWaterSolver/CMakeLists.txt;31;ADD_NEKTAR_TEST;/Users/schun/nektar/solvers/ShallowWaterSolver/CMakeLists.txt;0;")
add_test(ShallowWaterSolver_TestMMFSWEZonalSphere "/Users/schun/nektar/buildtest/tests/Tester" "/Users/schun/nektar/solvers/ShallowWaterSolver/Tests/TestMMFSWEZonalSphere.tst")
set_tests_properties(ShallowWaterSolver_TestMMFSWEZonalSphere PROPERTIES  _BACKTRACE_TRIPLES "/Users/schun/nektar/cmake/NektarCommon.cmake;263;ADD_TEST;/Users/schun/nektar/solvers/ShallowWaterSolver/CMakeLists.txt;32;ADD_NEKTAR_TEST;/Users/schun/nektar/solvers/ShallowWaterSolver/CMakeLists.txt;0;")
add_test(ShallowWaterSolver_TestMMFSWERossbySphere "/Users/schun/nektar/buildtest/tests/Tester" "/Users/schun/nektar/solvers/ShallowWaterSolver/Tests/TestMMFSWERossbySphere.tst")
set_tests_properties(ShallowWaterSolver_TestMMFSWERossbySphere PROPERTIES  _BACKTRACE_TRIPLES "/Users/schun/nektar/cmake/NektarCommon.cmake;263;ADD_TEST;/Users/schun/nektar/solvers/ShallowWaterSolver/CMakeLists.txt;33;ADD_NEKTAR_TEST;/Users/schun/nektar/solvers/ShallowWaterSolver/CMakeLists.txt;0;")
add_test(ShallowWaterSolver_LinearSWE_StandingWave_WallBC_CG_P4 "/Users/schun/nektar/buildtest/tests/Tester" "/Users/schun/nektar/solvers/ShallowWaterSolver/Tests/LinearSWE_StandingWave_WallBC_CG_P4.tst")
set_tests_properties(ShallowWaterSolver_LinearSWE_StandingWave_WallBC_CG_P4 PROPERTIES  _BACKTRACE_TRIPLES "/Users/schun/nektar/cmake/NektarCommon.cmake;263;ADD_TEST;/Users/schun/nektar/solvers/ShallowWaterSolver/CMakeLists.txt;35;ADD_NEKTAR_TEST;/Users/schun/nektar/solvers/ShallowWaterSolver/CMakeLists.txt;0;")
add_test(ShallowWaterSolver_LinearSWE_StandingWave_WallBC_CG_P8 "/Users/schun/nektar/buildtest/tests/Tester" "/Users/schun/nektar/solvers/ShallowWaterSolver/Tests/LinearSWE_StandingWave_WallBC_CG_P8.tst")
set_tests_properties(ShallowWaterSolver_LinearSWE_StandingWave_WallBC_CG_P8 PROPERTIES  _BACKTRACE_TRIPLES "/Users/schun/nektar/cmake/NektarCommon.cmake;263;ADD_TEST;/Users/schun/nektar/solvers/ShallowWaterSolver/CMakeLists.txt;36;ADD_NEKTAR_TEST;/Users/schun/nektar/solvers/ShallowWaterSolver/CMakeLists.txt;0;")
add_test(ShallowWaterSolver_LinearSWE_StandingWave_PeriodicBC_CG_P8 "/Users/schun/nektar/buildtest/tests/Tester" "/Users/schun/nektar/solvers/ShallowWaterSolver/Tests/LinearSWE_StandingWave_PeriodicBC_CG_P8.tst")
set_tests_properties(ShallowWaterSolver_LinearSWE_StandingWave_PeriodicBC_CG_P8 PROPERTIES  _BACKTRACE_TRIPLES "/Users/schun/nektar/cmake/NektarCommon.cmake;263;ADD_TEST;/Users/schun/nektar/solvers/ShallowWaterSolver/CMakeLists.txt;37;ADD_NEKTAR_TEST;/Users/schun/nektar/solvers/ShallowWaterSolver/CMakeLists.txt;0;")
add_test(ShallowWaterSolver_LinearSWE_StandingWave_WallBC_DG_P4 "/Users/schun/nektar/buildtest/tests/Tester" "/Users/schun/nektar/solvers/ShallowWaterSolver/Tests/LinearSWE_StandingWave_WallBC_DG_P4.tst")
set_tests_properties(ShallowWaterSolver_LinearSWE_StandingWave_WallBC_DG_P4 PROPERTIES  _BACKTRACE_TRIPLES "/Users/schun/nektar/cmake/NektarCommon.cmake;263;ADD_TEST;/Users/schun/nektar/solvers/ShallowWaterSolver/CMakeLists.txt;38;ADD_NEKTAR_TEST;/Users/schun/nektar/solvers/ShallowWaterSolver/CMakeLists.txt;0;")
add_test(ShallowWaterSolver_LinearSWE_StandingWave_WallBC_DG_P8 "/Users/schun/nektar/buildtest/tests/Tester" "/Users/schun/nektar/solvers/ShallowWaterSolver/Tests/LinearSWE_StandingWave_WallBC_DG_P8.tst")
set_tests_properties(ShallowWaterSolver_LinearSWE_StandingWave_WallBC_DG_P8 PROPERTIES  _BACKTRACE_TRIPLES "/Users/schun/nektar/cmake/NektarCommon.cmake;263;ADD_TEST;/Users/schun/nektar/solvers/ShallowWaterSolver/CMakeLists.txt;39;ADD_NEKTAR_TEST;/Users/schun/nektar/solvers/ShallowWaterSolver/CMakeLists.txt;0;")
add_test(ShallowWaterSolver_LinearSWE_StandingWave_PeriodicBC_DG_P8 "/Users/schun/nektar/buildtest/tests/Tester" "/Users/schun/nektar/solvers/ShallowWaterSolver/Tests/LinearSWE_StandingWave_PeriodicBC_DG_P8.tst")
set_tests_properties(ShallowWaterSolver_LinearSWE_StandingWave_PeriodicBC_DG_P8 PROPERTIES  _BACKTRACE_TRIPLES "/Users/schun/nektar/cmake/NektarCommon.cmake;263;ADD_TEST;/Users/schun/nektar/solvers/ShallowWaterSolver/CMakeLists.txt;40;ADD_NEKTAR_TEST;/Users/schun/nektar/solvers/ShallowWaterSolver/CMakeLists.txt;0;")
add_test(ShallowWaterSolver_NonlinearSWE_RossbyModon_CG_P9 "/Users/schun/nektar/buildtest/tests/Tester" "/Users/schun/nektar/solvers/ShallowWaterSolver/Tests/NonlinearSWE_RossbyModon_CG_P9.tst")
set_tests_properties(ShallowWaterSolver_NonlinearSWE_RossbyModon_CG_P9 PROPERTIES  _BACKTRACE_TRIPLES "/Users/schun/nektar/cmake/NektarCommon.cmake;263;ADD_TEST;/Users/schun/nektar/solvers/ShallowWaterSolver/CMakeLists.txt;41;ADD_NEKTAR_TEST;/Users/schun/nektar/solvers/ShallowWaterSolver/CMakeLists.txt;0;")
add_test(ShallowWaterSolver_NonlinearSWE_RossbyModon_DG_P9 "/Users/schun/nektar/buildtest/tests/Tester" "/Users/schun/nektar/solvers/ShallowWaterSolver/Tests/NonlinearSWE_RossbyModon_DG_P9.tst")
set_tests_properties(ShallowWaterSolver_NonlinearSWE_RossbyModon_DG_P9 PROPERTIES  _BACKTRACE_TRIPLES "/Users/schun/nektar/cmake/NektarCommon.cmake;263;ADD_TEST;/Users/schun/nektar/solvers/ShallowWaterSolver/CMakeLists.txt;42;ADD_NEKTAR_TEST;/Users/schun/nektar/solvers/ShallowWaterSolver/CMakeLists.txt;0;")
